### ISSUE TITLE
Restructure MST guide to follow convention used by Liberty guides

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microshed-testing#86]
Instead of instructing users to do incremental updates, restructure the guide to use the whole-class update approach in use by Liberty guides in general.

This makes it easier for users to switch between guides especially when guides are used in a workshop setting.

Cc @GraceJansen @jamiecoleman92 @gkwan-ibm

**Comment by gkwan-ibm** [comment]
close
- issue was addressed
